apiVersion: v1
kind: Namespace
metadata:
  name: sre-techtask

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dadjokes
  namespace: sre-techtask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dadjokes
  template:
    metadata:
      labels:
        app: dadjokes
    spec:
      containers:
      - name: dadjokes
        image: yesinteractive/dadjokes
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: dadjokes
  namespace: sre-techtask
spec:
  selector:
    app: dadjokes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8100
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dadjokes-ingress
  namespace: sre-techtask
spec:
  rules:
    - host: dadjokes.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dadjokes
                port:
                  number: 8100
